### PR TITLE
added proxy URL generation feature

### LINKED ISSUE #1: Add Proxy Link generation as Rest API endpoint
Add Proxy Link generation as Rest API endpoint

## Example

Request :- 
```
http://localhost:8021/generate/proxyURL?url=https://bravo68web.me/images/header_.png
```
Response (json) :- 
```
http://localhost:8021/fetch/image?key=aHR0cHM6Ly9icmF2bzY4d2ViLm1lL2ltYWdlcy9oZWFkZXJfLnBuZw==
```

Use base64 to encode.

### PR DESCRIPTION
**Pull request by Procoder16**
Contributed to issue #1.
Can you verify and merge the PR if valid.

### CODE REVIEW

**Review by BRAVO68WEB — APPROVED** [review]
Fine all checks done

**Comment by BRAVO68WEB** [comment]
Can you also update Readme?

**Comment by Procoder16** [comment]
> Can you also update Readme?

Yeah sure... I can do that.

**Comment by Procoder16** [comment]
@BRAVO68WEB I have updated the readme.
Verify the same and merge.

**Pull request merged**
